local builtin = require('telescope.builtin')
require'telescope'.load_extension('project')
vim.keymap.set('n', '<leader>tf', builtin.find_files, {})
vim.keymap.set('n', '<leader>tg', builtin.git_files, {})
vim.keymap.set('n', '<leader>tr', function()
    builtin.live_grep({ search = vim.fn.input("Grep > ") })
end)
vim.keymap.set('n', '<leader>tb', builtin.buffers, {})
vim.keymap.set('n', '<leader>tc', builtin.commands, {})
vim.keymap.set('n', '<leader>tp', function()
    require'telescope'.extensions.project.project{}
end)
