vim.opt.guicursor = "i:blinkon300-blinkoff10"
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true
vim.opt.nu = true -- line numbers
vim.opt.relativenumber = true
vim.opt.smartindent = true
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.termguicolors = true
vim.opt.scrolloff = 8
vim.opt.signcolumn = "yes"
vim.opt.isfname:append("@-@")
vim.opt.updatetime = 50
vim.opt.colorcolumn = "80"
vim.opt.backup = true
vim.opt.backupdir = os.getenv("HOME") .. "/.vim/vimswp"
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undolevels=1000
vim.opt.undoreload=10000
vim.opt.undofile = true
vim.opt.signcolumn = "yes"
