---

- name: Install common desktop stuff 
  pacman:
    name:
      - alacritty 
      - blueman
      - catfish  # file search
      - dex
      - engrampa
      - exfat-utils
      - firefox 
      - flatpak
      - flameshot
      - ghostty
      - gnome-keyring
      - gvfs  # trash, mount with udisk and remote fs
      - i3status-rust
      - mpv
      - network-manager-applet
      - ntfs-3g
      - pipewire
      - pipewire-alsa
      - pipewire-pulse
      - solaar
      - syncthing
      - thunar  # file manager
      - thunar-archive-plugin  # zip/unzip
      - thunar-media-tags-plugin  # view/edit ID3 tags
      - thunar-volman  # removable device manager
      - thunderbird
      - ttf-jetbrains-mono-nerd
      - tumbler  # thumb preview
      - udiskie
      - udisks2
      - wezterm
    state: present
  become: yes

- name: Enable system services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  become: yes
  loop:
    - udisks2.service
    - bluetooth.service
    - NetworkManager.service
    - "syncthing@{{ user }}.service"

- name: Create udiskie systemd user service
  copy:
    content: |
      [Unit]
      Description=Removable drive automounter
      After=graphical-session.target
      
      [Service]
      Type=simple
      ExecStart=/usr/bin/udiskie --tray
      Restart=always
      
      [Install]
      WantedBy=default.target
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/udiskie.service"

- name: Enable and start user services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
    scope: user
  loop:
    - pipewire.service
    - pipewire-pulse.service
    - udiskie.service
    - wireplumber.service

- name: Install flatpak packages
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - com.saivert.pwvucontrol

- name: Install AUR packages
  kewlfft.aur.aur:
    name:
      - 1password
    state: present


# steps for solaar work without sudo
- name: Ensure group "plugdev" exists
  ansible.builtin.group:
    name: plugdev 
    state: present
  become: yes
    
- name: Add user to additional groups
  user:
    name: "{{ user }}"
    groups: 
      - plugdev  
  become: yes

