---
- name: Install common dev stuff 
  pacman:
    name:
      - docker
      - docker-compose
      - go
      - npm
      - ripgrep
      - uv 
      - wakatime
    state: present
  become: yes

- name: Install AUR dev packages
  kewlfft.aur.aur:
    name:
      - visual-studio-code-bin 
    state: present

- name: Add user to additional groups
  user:
    name: "{{ user }}"
    groups: 
  become: yes
