---
- name: Install common dev stuff 
  pacman:
    name:
      - go
      - ripgrep
      - uv 
      - wakatime
    state: present
  become: yes

- name: Install AUR dev packages
  kewlfft.aur.aur:
    name:
      - visual-studio-code-bin 
    state: present

