---
- name: Configure Arch Linux System
  hosts: localhost
  connection: local
  vars:
    user: "{{ ansible_user_id }}"
    wayland_hosts:
      - "mars"
    desktop_hosts:
      - "mars"
      - "jupiter"
    xorg_hosts:
      - "jupiter"
    dev_hosts:
      - "mars"
      - "jupiter"
    nvidia:
      - "jupiter"

  tasks:
    - import_tasks: packages.yml
    - import_tasks: dotfiles.yml
    - import_tasks: sway.yml
      when: ansible_hostname in wayland_hosts
    - import_tasks: i3.yml
      when: ansible_hostname in xorg_hosts
    - import_tasks: desktop.yml
      when: ansible_hostname in desktop_hosts
    - import_tasks: services.yml
    - import_tasks: users.yml
    - import_tasks: dev.yml
      when: ansible_hostname in dev_hosts
    - import_tasks: nvidia.yml
      when: ansible_hostname in nvidia 
