---
- name: Install essential packages
  pacman:
    name:
      - atuin
      - chezmoi
      - direnv
      - git
      - less
      - neovim
      - polkit-gnome
      - starship
      - tailscale
      - tmux
      - zsh
    state: present
  become: yes

- name: Check if paru is installed
  command: which paru
  register: paru_check
  failed_when: false
  changed_when: false

- name: Install paru AUR helper
  shell: |
    cd /tmp
    git clone https://aur.archlinux.org/paru.git
    cd paru
    makepkg -si --noconfirm
  when: paru_check.rc != 0

- name: Install AUR packages
  kewlfft.aur.aur:
    name:
      - 1password
    state: present
