---
- name: Install essential packages
  pacman:
    name:
      - atuin
      - chezmoi
      - direnv
      - fzf
      - git
      - htop
      - linux-firmware
      - less
      - neovim
      - polkit-gnome
      - rsync
      - smartmontools
      - starship
      - tailscale
      - tmux
      - yazi
      - zsh
      - zsh-completions
    state: present
  become: yes

- name: Check if paru is installed
  command: which paru
  register: paru_check
  failed_when: false
  changed_when: false

- name: Install paru AUR helper
  shell: |
    cd /tmp
    git clone https://aur.archlinux.org/paru.git
    cd paru
    makepkg -si --noconfirm
  when: paru_check.rc != 0

