---
- name: Bootstrap Arch Linux Desktop
  hosts: localhost
  connection: local
  become: yes
  
  vars:
    packages:
      # Sway window manager and related
      - sway
      - swayidle
      - swaylock
      # - waybar
      # - wofi
      # - mako
      
      # AMD drivers
      # - mesa
      # - lib32-mesa
      # - vulkan-radeon
      # - lib32-vulkan-radeon
      # - xf86-video-amdgpu
      
      # Applications
      - alacritty
      - firefox
      
      # Essential utilities
      # - wl-clipboard
      # - grim
      # - slurp
      # - brightnessctl
      # - playerctl

  tasks:
    - name: Update package cache
      pacman:
        update_cache: yes

    - name: Install packages
      pacman:
        name: "{{ packages }}"
        state: present
