---
- name: Bootstrap Arch Linux Desktop
  hosts: localhost
  connection: local
  become: yes
  
  vars:
    user_home: "{{ lookup('env', 'HOME') }}"
    current_user: "{{ lookup('env', 'USER') }}"
    packages:
      # base
      - less
      - openssh
      - zsh
      - man
      # Sway window manager and related
      - sway
      - swayidle
      - swaylock
      - ttf-jetbrains-mono-nerd
      - i3status-rust 
      - xorg-xwayland
      # - rofi
      # - waybar
      - wofi
      # - mako
      
      # AMD drivers
      # - mesa
      # - lib32-mesa
      # - vulkan-radeon
      # - lib32-vulkan-radeon
      # - xf86-video-amdgpu
      
      # Applications
      - alacritty
      - firefox
      - chezmoi
      - nvim
      
      # Essential utilities
      # - wl-clipboard
      # - grim
      # - slurp
      # - brightnessctl
      # - playerctl
    aur_packages:
      - 1password

  tasks:
    - name: Update package cache
      pacman:
        update_cache: yes

    - name: Install packages
      pacman:
        name: "{{ packages }}"
        state: present

    - name: create .config directory
      file:
        path: "{{ user_home }}/.config"
        state: directory
        owner: "{{ current_user }}"
        mode: '0755'
      become: no
    
    - name: Check if paru is installed
      command: which paru
      register: paru_check
      failed_when: false
      changed_when: false
      become: no

    - name: Clone paru repository
      git:
        repo: https://aur.archlinux.org/paru.git
        dest: "{{ user_home }}/paru"
        force: yes
      when: paru_check.rc != 0
      become: no

    - name: Build and install paru
      shell: |
        cd {{ user_home }}/paru
        makepkg -si --noconfirm
      when: paru_check.rc != 0
      become: no

    - name: clean up paru build
      file:
        path: "{{ user_home }}/paru"
        state: absent
      when: paru_check.rc != 0
      become: no

    - name: install AUR packages with paru
      shell: paru -S --noconfirm {{ item }}
      loop: "{{ aur_packages }}"
      become: no

