---
- name: Bootstrap Arch Linux Desktop
  hosts: localhost
  connection: local
  become: yes
  
  vars:
    user_home: "{{ lookup('env', 'HOME') }}"
    current_user: "{{ lookup('env', 'USER') }}"
    packages:
      # base
      - keychain
      - less
      - libayatana-appindicator
      - libappindicator-gtk3
      - linux-headers
      - man
      - openssh
      - org.freedesktop.secrets
      - zsh
      # Sway window manager and related
      # - mako
      - i3status-rust 
      - sway
      - swayidle
      - swaylock
      - rofi
      - ttf-jetbrains-mono-nerd
      # - waybar
      - wofi
      - xorg-xwayland
      
      # AMD drivers
      # - mesa
      # - lib32-mesa
      # - vulkan-radeon
      # - lib32-vulkan-radeon
      # - xf86-video-amdgpu
      
      # Applications
      - alacritty
      - atuin
      - chezmoi
      - firefox
      - nvim
      - thunderbird

      # dev
      - direnv
      - fzf
      
      # Essential utilities
      # - wl-clipboard
      # - grim
      # - slurp
      # - brightnessctl
      # - playerctl
    aur_packages:
      - 1password
      - tuxedo-control-center-bin
      - visual-studio-code-bin
      - icu69-bin

  tasks:
    - name: Update package cache
      pacman:
        update_cache: yes

    - name: Install packages
      pacman:
        name: "{{ packages }}"
        state: present

    - name: Change user default to zsh
      user:
        name: "{{ current_user }}"
        shell: /usr/bin/zsh
      become: yes

    - name: Add user to sudoers with passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ current_user }}\s'
        line: '{{ current_user }} ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      become: yes 

    - name: create .config directory
      file:
        path: "{{ user_home }}/.config"
        state: directory
        owner: "{{ current_user }}"
        mode: '0755'
      become: no
    
    - name: Check if paru is installed
      command: which paru
      register: paru_check
      failed_when: false
      changed_when: false
      become: no

    - name: Clone paru repository
      git:
        repo: https://aur.archlinux.org/paru.git
        dest: "{{ user_home }}/paru"
        force: yes
      when: paru_check.rc != 0
      become: no

    - name: Build and install paru
      shell: |
        cd {{ user_home }}/paru
        makepkg -si --noconfirm
      when: paru_check.rc != 0
      become: no

    - name: clean up paru build
      file:
        path: "{{ user_home }}/paru"
        state: absent
      when: paru_check.rc != 0
      become: no

    # commented for now, as this is running every time, and reinstalling
    # everytime, I need to find a better solution
    # - name: install AUR packages with paru
    #   shell: paru -S --noconfirm {{ item }}
    #   loop: "{{ aur_packages }}"
    #   become: no
    #
